CREATE TABLE IF NOT EXISTS events (
    id SERIAL PRIMARY KEY,
    detected_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    severity TEXT NOT NULL,
    g_force_value DOUBLE PRECISION NOT NULL,
    is_false_alarm BOOLEAN NOT NULL DEFAULT FALSE
);
